### PR TITLE
[WIP] Factor cursor to its own crate & Headline parser

### PR DESCRIPTION
**Pull request by ngortheone**

### CODE REVIEW

**Comment by ngortheone** [comment]
@asa-z @scarab5q  I've elevated your access to admin so you can merge PRs even if they are not reviewed.
I think this is a necessary measure for now, since we don't have any number of constant collaborators. Even a single person willing to contribute should be able to do this with minimal resistance.

**Comment by ngortheone** [comment]
I think this was the last thing I've worked on here. And I started quite a big refactoring, which to be honest I don't think is too necessary. Feel free to extract useful bits from here and drop the rest.

**Comment by agathazeren** [comment]
I have a busy weekend and this is going to take a while to review, but I will try to go through and pull out the bits I think are good in the coming weeks.

**Comment by agathazeren** [comment]
From a discussion on gitter, @ngortheone and I came to the conclusion to not attempt to factor out the cursor at this time, as even though the ideas are very interesting, and worthy of further effort, it is better to focus more on the org-rs core functionality at this time.

**Pull request closed without merging**
