### PR TITLE
Derive Debug, Clone, and PartialEq to types, where applicable

### PR DESCRIPTION
**Pull request by agathazeren**

### CODE REVIEW

**Review by appetrosyan — APPROVED** [review]
LGTM.

**Comment by appetrosyan** [comment]
Given that this PR has many trivial conflicts, I'd suggest resolving them in a rebase.

**Comment by ngortheone** [comment]
@appetrosyan given low engagement on this project I would recommend you fix trivial issues in pull requests you find useful yourself and merging them without waiting for the author to show up (it may be a while).

**Comment by appetrosyan** [comment]
In that case I’ll prune these over the next week.

**Comment by appetrosyan** [comment]
@agathazeren given that a few of your other PRs don't depend on this functionality, would you be happy postponing its merge? As of right now, there doesn't seem to be pressure to derive those traits, so given the amount of work that you'd need to do, I'd recommend that we close it for the time being, and if the need arises create a new one later.

**Pull request closed without merging**
